### ISSUE TITLE
bug found

### ISSUE THREAD

**Issue by alliuo** [AaronJing/ApproxTrain#1]
Hello, 
Thank for your opening source. I tried running your code but seems to have found some bug. 
https://github.com/AaronJing/ApproxTrain/blob/3f1a7b0fb4fc64a2df8044c98b77d836a01c38d1/cuda/AMsimulator.inl#L21-L23
_For CARRY_MASK=0x80 and CLEAR_CARRY_MASK=0x7f, the  mantissa and carry will always be 0._
Could you solve it ? Thanks again.

**Comment by AaronJing** [comment]
Hi,

The carry flag (from normalisation) is stored at MSB of lookup table entry which is bit 7 for the Bfloat. Therefore, we use bitwise AND operator and carry mask 0x80 (0b1000 0000) to extract the carry bit. Then, we simply clear carry bit (bit 7 for the Bfloat) by ANDing with mask 0x7f (0b0111 1111) to obtain the mantissa part. I hope this helps.

**Comment by alliuo** [comment]
> Hi,
> 
> The carry flag (from normalisation) is stored at MSB of lookup table entry which is bit 7 for the Bfloat. Therefore, we use bitwise AND operator and carry mask 0x80 (0b1000 0000) to extract the carry bit. Then, we simply clear carry bit (bit 7 for the Bfloat) by ANDing with mask 0x7f (0b0111 1111) to obtain the mantissa part. I hope this helps.

Thank for your reply.
But for _Line 21_ , the _Mbm_mantmult_ will be shift left for 16 bit (for Bfloat), and the lower eight bits will be 0.
I found this error because I ran different multipliers but got the same result.

**Comment by AaronJing** [comment]
> 

Hi,

You are correct. The shift should not be there (line 21). I have moved the shift to line 23 to get the proper carry and mantissa. Thanks for spotting this. 

Closing this now.

**Comment by alliuo** [comment]
> > 
> 
> Hi,
> 
> You are correct. The shift should not be there (line 21). I have moved the shift to line 23 to get the proper carry and mantissa. Thanks for spotting this.
> 
> Closing this now.

https://github.com/AaronJing/ApproxTrain/blob/e3b0291d03a9b970ca0b78e8790195850b3b4690/cuda/AMsimulator.inl#L22

Hello, I think it's should be **_>>7_**
 :)

**Comment by AaronJing** [comment]
> > > 
> > 
> > 
> > Hi,
> > You are correct. The shift should not be there (line 21). I have moved the shift to line 23 to get the proper carry and mantissa. Thanks for spotting this.
> > Closing this now.
> 
> https://github.com/AaronJing/ApproxTrain/blob/e3b0291d03a9b970ca0b78e8790195850b3b4690/cuda/AMsimulator.inl#L22
> 
> Hello, I think it's should be **_>>7_** :)

Hi,

Thanks for raising this. I ran the mnist_example.py before the push and got 97% accuracy, leading me to think the issue had been fixed. However, after fixing line22, I consistently achieve 98%. We need to come up with a better way to test the implementation.
